"""add about author2

Revision ID: 95db0e3327d2
Revises: 19d007359921
Create Date: 2022-08-26 14:39:12.549459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95db0e3327d2'
down_revision = '19d007359921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['poster_id'], ['id'])
    op.drop_column('posts', 'author')
    op.add_column('users', sa.Column('about_author', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_author')
    op.add_column('posts', sa.Column('author', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###
